/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Clases.GuradarConfiguracion;
import Clases.Jugadores;
import Clases.Usuarios;
import static Main.Crear_Usuario.usersGuardados;
import static Main.Inicio_de_Sesion.cantidadUsers;
import static Main.Inicio_de_Sesion.usuarioLogin;
import javax.swing.JOptionPane;

/**
 *
 * @author adalb
 */
public class Configuracion extends javax.swing.JFrame {

    /**
     * Creates new form Configuracion
     */
    public Configuracion() {
        initComponents();
    }
    static GuradarConfiguracion confi;
    static GuradarConfiguracion llamar1=new GuradarConfiguracion(0,0,0,false,"","");
    static Jugadores[] jugadores=new Jugadores[8];
    public static Jugadores llamar2=new Jugadores("","","");
    public static String efectodeReyes="Intercambiar carta", efectodeReinas="Intercambiar carta",equipo;
    public static String jugador1,jugador2,jugador3,jugador4,jugador5,jugador6,jugador7,jugador8,jugador9,jugador10,fichaDeEquipo1,fichaDeEquipo2,fichaDeEquipo3;
    public static int cantidadJugadores=4,cantidadCartas=7,paraIndice=1;
    public static boolean puedeConfirmar=false,configuracion=false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreJugador3 = new javax.swing.JLabel();
        nombreJugador1 = new javax.swing.JLabel();
        nombreJugador2 = new javax.swing.JLabel();
        CantidadJugadores = new javax.swing.JComboBox<>();
        jugadoresdeequipo3 = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jugadoresdeequipo1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jugadoresdeequipo2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        fichasequipo1 = new javax.swing.JLabel();
        fichasdequipo1 = new javax.swing.JComboBox<>();
        fichasequipo2 = new javax.swing.JLabel();
        fichasdequipo2 = new javax.swing.JComboBox<>();
        fichasequipo3 = new javax.swing.JLabel();
        fichasdequipo3 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        efectoDeReyes = new javax.swing.JLabel();
        efectoReyes = new javax.swing.JComboBox<>();
        efectoDeReyes1 = new javax.swing.JLabel();
        efectoReinas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        equipoDeJugador = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreJugador3.setText("Cantidad de jugadores:");
        getContentPane().add(nombreJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, 24));

        nombreJugador1.setText("Cantidad de jugadores:");
        getContentPane().add(nombreJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 24));

        nombreJugador2.setText("Cantidad de jugadores:");
        getContentPane().add(nombreJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, 24));

        CantidadJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "6", "8" }));
        jComboBox1.setVisible(false);
        nombreJugador1.setText(usuarioLogin);
        nombreJugador2.setVisible(false);
        nombreJugador3.setVisible(false);
        fichasequipo3.setVisible(false);
        fichasdequipo3.setVisible(false);
        jugadoresdeequipo3.setVisible(false);
        jComboBox3.setVisible(false);
        jComboBox4.setVisible(false);
        jComboBox5.setVisible(false);
        jComboBox6.setVisible(false);
        jComboBox7.setVisible(false);
        jComboBox8.setVisible(false);
        jComboBox9.setVisible(false);
        jComboBox10.setVisible(false);
        CantidadJugadores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CantidadJugadoresItemStateChanged(evt);
            }
        });
        getContentPane().add(CantidadJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 43, 88, -1));

        jugadoresdeequipo3.setText("Jugadores de equipo 3:");
        getContentPane().add(jugadoresdeequipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, 24));

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        cancelar.setText("Cancelar");
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        jComboBox1.setActionCommand("");
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        for(int i=0;i<usersGuardados.size();i++){
            jComboBox1.addItem(usersGuardados.get(i).getUser());
        }
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, -1));

        jugadoresdeequipo1.setText("Jugadores de equipo 1:");
        getContentPane().add(jugadoresdeequipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 24));

        jComboBox2.setActionCommand("");
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        for(int i=0;i<usersGuardados.size();i++){
            jComboBox2.addItem(usersGuardados.get(i).getUser());
        }
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 120, -1));

        jugadoresdeequipo2.setText("Jugadores de equipo 2:");
        getContentPane().add(jugadoresdeequipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, 24));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        for(int i=0;i<usersGuardados.size();i++){
            jComboBox3.addItem(usersGuardados.get(i).getUser());
        }
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 120, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        for(int i=0;i<usersGuardados.size();i++){
            jComboBox4.addItem(usersGuardados.get(i).getUser());
        }
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        for(int i=0;i<usersGuardados.size();i++){
            jComboBox5.addItem(usersGuardados.get(i).getUser());
        }
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 120, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        for(int i=0;i<usersGuardados.size();i++){
            jComboBox6.addItem(usersGuardados.get(i).getUser());
        }
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 120, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        for(int i=0;i<usersGuardados.size();i++){
            jComboBox7.addItem(usersGuardados.get(i).getUser());
        }
        getContentPane().add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        for(int i=0;i<usersGuardados.size();i++){
            jComboBox8.addItem(usersGuardados.get(i).getUser());
        }
        getContentPane().add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 120, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        for(int i=0;i<usersGuardados.size();i++){
            jComboBox9.addItem(usersGuardados.get(i).getUser());
        }
        getContentPane().add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 120, -1));

        fichasequipo1.setText("Fichas de equipo 1:");
        getContentPane().add(fichasequipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 24));

        fichasdequipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rojo", "verde", "azul", "amarillo" }));
        getContentPane().add(fichasdequipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 88, -1));

        fichasequipo2.setText("Fichas de equipo 2:");
        getContentPane().add(fichasequipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, 24));

        fichasdequipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rojo", "verde", "azul", "amarillo" }));
        getContentPane().add(fichasdequipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 88, -1));

        fichasequipo3.setText("Fichas de equipo 3:");
        getContentPane().add(fichasequipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, 24));

        fichasdequipo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rojo", "verde", "azul", "amarillo" }));
        getContentPane().add(fichasdequipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 88, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));
        for(int i=0;i<usersGuardados.size();i++){
            jComboBox9.addItem(usersGuardados.get(i).getUser());
        }
        getContentPane().add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 120, -1));

        efectoDeReyes.setText("Efecto de cartas Reyes:");
        getContentPane().add(efectoDeReyes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, 24));

        efectoReyes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Intercambiar carta", "Intercambiar ficha" }));
        getContentPane().add(efectoReyes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 88, -1));

        efectoDeReyes1.setText("Efecto de cartas Reinas:");
        getContentPane().add(efectoDeReyes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, 24));

        efectoReinas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Intercambiar carta", "Intercambiar ficha" }));
        getContentPane().add(efectoReinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 88, -1));

        jLabel4.setText("Escoja su equipo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, 24));

        equipoDeJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo 1", "Equipo 2" }));
        equipoDeJugador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                equipoDeJugadorItemStateChanged(evt);
            }
        });
        getContentPane().add(equipoDeJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 88, -1));

        jLabel5.setText("Cantidad de jugadores:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 43, -1, 24));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CantidadJugadoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CantidadJugadoresItemStateChanged
        // TODO add your handling code here:
        String cantidad=(String)CantidadJugadores.getSelectedItem();
        cantidadJugadores=Integer.parseInt(cantidad);
        equipo=(String)equipoDeJugador.getSelectedItem();
        switch(cantidadJugadores){
            case 2:
                switch(equipo){
                    case "Equipo 1":
                        nombreJugador1.setText(usuarioLogin);
                        nombreJugador1.setVisible(true);
                        nombreJugador2.setVisible(false);
                        nombreJugador3.setVisible(false);
                        jComboBox1.setVisible(false);
                        jComboBox2.setVisible(true);
                        jComboBox3.setVisible(false);
                        break;
                    case "Equipo 2":
                        nombreJugador2.setText(usuarioLogin);
                        nombreJugador1.setVisible(false);
                        nombreJugador2.setVisible(true);
                        nombreJugador3.setVisible(false);
                        jComboBox1.setVisible(true);
                        jComboBox2.setVisible(false);
                        jComboBox3.setVisible(false);
                        break;
                    case "Equipo 3":
                        nombreJugador3.setText(usuarioLogin);
                        nombreJugador1.setVisible(false);
                        nombreJugador2.setVisible(false);
                        nombreJugador3.setVisible(true);
                        jComboBox1.setVisible(true);
                        jComboBox2.setVisible(true);
                        jComboBox3.setVisible(false);
                        break;
                }
                equipoDeJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo 1", "Equipo 2" }));
                fichasdequipo3.setVisible(false);
                jugadoresdeequipo3.setVisible(false);
                jComboBox3.setVisible(false);
                jComboBox4.setVisible(false);
                jComboBox5.setVisible(false);
                jComboBox6.setVisible(false);
                jComboBox7.setVisible(false);
                jComboBox8.setVisible(false);
                jComboBox9.setVisible(false);
                jComboBox10.setVisible(false);
                break;
            case 3:
                switch(equipo){
                    case "Equipo 1":
                        nombreJugador1.setText(usuarioLogin);
                        nombreJugador1.setVisible(true);
                        nombreJugador2.setVisible(false);
                        nombreJugador3.setVisible(false);
                        jComboBox1.setVisible(false);
                        jComboBox2.setVisible(true);
                        jComboBox3.setVisible(true);
                        break;
                    case "Equipo 2":
                        nombreJugador2.setText(usuarioLogin);
                        nombreJugador1.setVisible(false);
                        nombreJugador2.setVisible(true);
                        nombreJugador3.setVisible(false);
                        jComboBox1.setVisible(true);
                        jComboBox2.setVisible(false);
                        jComboBox3.setVisible(true);
                        break;
                    case "Equipo 3":
                        nombreJugador3.setText(usuarioLogin);
                        nombreJugador1.setVisible(false);
                        nombreJugador2.setVisible(false);
                        nombreJugador3.setVisible(true);
                        jComboBox1.setVisible(true);
                        jComboBox2.setVisible(true);
                        jComboBox3.setVisible(false);
                        break;
                }
                equipoDeJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo 1", "Equipo 2","Equipo 3" }));
                fichasequipo3.setVisible(true);
                fichasdequipo3.setVisible(true);
                jugadoresdeequipo3.setVisible(true);
                jComboBox4.setVisible(false);
                jComboBox5.setVisible(false);
                jComboBox6.setVisible(false);
                jComboBox7.setVisible(false);
                jComboBox8.setVisible(false);
                jComboBox9.setVisible(false);
                jComboBox10.setVisible(false);
                break;  
            case 4:
                switch(equipo){
                    case "Equipo 1":
                        nombreJugador1.setText(usuarioLogin);
                        nombreJugador1.setVisible(true);
                        nombreJugador2.setVisible(false);
                        nombreJugador3.setVisible(false);
                        jComboBox1.setVisible(false);
                        jComboBox2.setVisible(true);
                        jComboBox3.setVisible(false);
                        break;
                    case "Equipo 2":
                        nombreJugador2.setText(usuarioLogin);
                        nombreJugador1.setVisible(false);
                        nombreJugador2.setVisible(true);
                        nombreJugador3.setVisible(false);
                        jComboBox1.setVisible(true);
                        jComboBox2.setVisible(false);
                        jComboBox3.setVisible(false);
                        break;
                    case "Equipo 3":
                        nombreJugador3.setText(usuarioLogin);
                        nombreJugador1.setVisible(false);
                        nombreJugador2.setVisible(false);
                        nombreJugador3.setVisible(true);
                        jComboBox1.setVisible(true);
                        jComboBox2.setVisible(true);
                        jComboBox3.setVisible(false);
                        break;
                }
                equipoDeJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo 1", "Equipo 2" }));
                fichasequipo3.setVisible(false);
                fichasdequipo3.setVisible(false);
                jugadoresdeequipo3.setVisible(false);
                jComboBox4.setVisible(true);
                jComboBox5.setVisible(true);
                jComboBox6.setVisible(false);
                jComboBox7.setVisible(false);
                jComboBox8.setVisible(false);
                jComboBox9.setVisible(false);
                jComboBox10.setVisible(false);
                break;   
            case 6:
                if(cantidadUsers<6){
                    JOptionPane.showMessageDialog(null, "No hay suficientes usuarios.");
                }else{
                    CantidadJugadores.setSelectedIndex(0);
                    switch(equipo){
                        case "Equipo 1":
                            nombreJugador1.setText(usuarioLogin);
                            nombreJugador1.setVisible(true);
                            nombreJugador2.setVisible(false);
                            nombreJugador3.setVisible(false);
                            jComboBox1.setVisible(false);
                            jComboBox2.setVisible(true);
                            jComboBox3.setVisible(true);
                            break;
                        case "Equipo 2":
                            nombreJugador2.setText(usuarioLogin);
                            nombreJugador1.setVisible(false);
                            nombreJugador2.setVisible(true);
                            nombreJugador3.setVisible(false);
                            jComboBox1.setVisible(true);
                            jComboBox2.setVisible(false);
                            jComboBox3.setVisible(true);
                            break;
                        case "Equipo 3":
                            nombreJugador3.setText(usuarioLogin);
                            nombreJugador1.setVisible(false);
                            nombreJugador2.setVisible(false);
                            nombreJugador3.setVisible(true);
                            jComboBox1.setVisible(true);
                            jComboBox2.setVisible(true);
                            jComboBox3.setVisible(false);
                            break;
                    }
                    equipoDeJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo 1", "Equipo 2","Equipo 3" }));
                    fichasequipo3.setVisible(true);
                    fichasdequipo3.setVisible(true);
                    jugadoresdeequipo3.setVisible(true);
                    jComboBox4.setVisible(true);
                    jComboBox5.setVisible(true);
                    jComboBox6.setVisible(true);
                    jComboBox7.setVisible(false);
                    jComboBox8.setVisible(false);
                    jComboBox9.setVisible(false);
                    jComboBox10.setVisible(false);
                }
                break;  
            case 8:
                if(cantidadUsers<6){
                    JOptionPane.showMessageDialog(null, "No hay suficientes usuarios.");
                }else{
                    CantidadJugadores.setSelectedIndex(0);
                    switch(equipo){
                        case "Equipo 1":
                            nombreJugador1.setText(usuarioLogin);
                            nombreJugador1.setVisible(true);
                            nombreJugador2.setVisible(false);
                            nombreJugador3.setVisible(false);
                            jComboBox1.setVisible(false);
                            jComboBox2.setVisible(true);
                            jComboBox3.setVisible(false);
                            break;
                        case "Equipo 2":
                            nombreJugador2.setText(usuarioLogin);
                            nombreJugador1.setVisible(false);
                            nombreJugador2.setVisible(true);
                            nombreJugador3.setVisible(false);
                            jComboBox1.setVisible(true);
                            jComboBox2.setVisible(false);
                            jComboBox3.setVisible(false);
                            break;
                        case "Equipo 3":
                            nombreJugador3.setText(usuarioLogin);
                            nombreJugador1.setVisible(false);
                            nombreJugador2.setVisible(false);
                            nombreJugador3.setVisible(true);
                            jComboBox1.setVisible(true);
                            jComboBox2.setVisible(true);
                            jComboBox3.setVisible(false);
                            break;
                    }
                    equipoDeJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo 1", "Equipo 2" }));
                    fichasequipo3.setVisible(false);
                    fichasdequipo3.setVisible(false);
                    jugadoresdeequipo3.setVisible(false);
                    jComboBox3.setVisible(false);
                    jComboBox4.setVisible(true);
                    jComboBox5.setVisible(true);
                    jComboBox6.setVisible(false);
                    jComboBox7.setVisible(true);
                    jComboBox8.setVisible(true);
                    jComboBox9.setVisible(true);
                    jComboBox10.setVisible(true);
                    }
                break;    
        }        
    }//GEN-LAST:event_CantidadJugadoresItemStateChanged

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        // TODO add your handling code here:
        puedeConfirmar=true;
        String[] revisar=new String[9];
        equipo=(String)equipoDeJugador.getSelectedItem();
        switch(equipo){
            case "Equipo 1":
                jugador1=usuarioLogin;
                jugador2=(String)jComboBox2.getSelectedItem();
                jugador3=(String)jComboBox3.getSelectedItem();
                break;
            case "Equipo 2":
                jugador1=(String)jComboBox1.getSelectedItem();
                jugador2=usuarioLogin;
                jugador3=(String)jComboBox3.getSelectedItem();
                break;
            case "Equipo 3":
                jugador1=(String)jComboBox1.getSelectedItem();
                jugador2=(String)jComboBox2.getSelectedItem();
                jugador3=usuarioLogin;
                break;
        }
        String cantidad=(String)CantidadJugadores.getSelectedItem();
        cantidadJugadores=Integer.parseInt(cantidad);
        jugador4=(String)jComboBox4.getSelectedItem();
        jugador5=(String)jComboBox5.getSelectedItem();
        jugador6=(String)jComboBox6.getSelectedItem();
        jugador7=(String)jComboBox7.getSelectedItem();
        jugador8=(String)jComboBox8.getSelectedItem();
        jugador9=(String)jComboBox9.getSelectedItem();
        jugador10=(String)jComboBox9.getSelectedItem();
        revisar[0]=jugador1;
        revisar[1]=jugador2;
        revisar[2]=jugador3;
        revisar[3]=jugador4;
        revisar[4]=jugador5;
        revisar[5]=jugador6;
        revisar[6]=jugador7;
        revisar[7]=jugador8;
        revisar[8]=jugador9;
        fichaDeEquipo1=(String)fichasdequipo1.getSelectedItem();
        fichaDeEquipo2=(String)fichasdequipo2.getSelectedItem();
        fichaDeEquipo3=(String)fichasdequipo3.getSelectedItem();
        efectodeReyes=(String)efectoReyes.getSelectedItem();
        efectodeReinas=(String)efectoReinas.getSelectedItem();
        switch(cantidadJugadores){
            case 2:
                if(jugador1.equals("")&&jugador2.equals("")){
                    JOptionPane.showMessageDialog(null, "Asegurese de escoger los jugadores.");
                    puedeConfirmar=false;
                }else{
                    if(fichaDeEquipo1.equals(fichaDeEquipo2)&&fichaDeEquipo2.equals(fichaDeEquipo1)){
                        JOptionPane.showMessageDialog(null, "Asegurese de escoger bien las fichas.");
                        puedeConfirmar=false;
                    }else{
                        for(int indice=0;indice<2;indice++){
                            for(int contar=0;contar<2;contar++){
                                if(indice!=contar){
                                    if(revisar[indice].equals(revisar[contar])){
                                        puedeConfirmar=false;
                                    }
                                }
                            }
                        }
                        if(puedeConfirmar==true){
                            JOptionPane.showMessageDialog(null, "Cambios guardados.");
                            jugadores[0]=new Jugadores("Equipo 1",jugador1,fichaDeEquipo1);
                            jugadores[1]=new Jugadores("Equipo 2",jugador2,fichaDeEquipo2);
                            llamar2.guardarJugadores(jugadores, "datos.Jugadores");
                            cantidadCartas=7;
                            paraIndice=0;
                            configuracion=true;
                            confi=new GuradarConfiguracion(cantidadJugadores,cantidadCartas,paraIndice,configuracion,efectodeReyes,efectodeReinas);
                            llamar1.guardarConfiguracion(confi, "datos.Configuracion");
                            new Menu_Principal().setVisible(true);
                            this.setVisible(false);
                        }else{
                            JOptionPane.showMessageDialog(null, "Asegurese de no repetir los jugadores.");
                        }
                    }
                }
                break;
            case 3:
                if(jugador1.equals("")&&jugador2.equals("")&&jugador3.equals("")){
                    JOptionPane.showMessageDialog(null, "Asegurese de escoger los jugadores.");
                    puedeConfirmar=false;
                }else{
                    if(fichaDeEquipo1.equals(fichaDeEquipo2)&&fichaDeEquipo1.equals(fichaDeEquipo3)
                            &&fichaDeEquipo2.equals(fichaDeEquipo1)&&fichaDeEquipo2.equals(fichaDeEquipo3)
                            &&fichaDeEquipo3.equals(fichaDeEquipo1)&&fichaDeEquipo3.equals(fichaDeEquipo2)){
                        JOptionPane.showMessageDialog(null, "Asegurese de escoger bien las fichas.");
                        puedeConfirmar=false;
                    }else{
                        for(int indice=0;indice<3;indice++){
                            for(int contar=0;contar<3;contar++){
                                if(indice!=contar){
                                    if(revisar[indice].equals(revisar[contar])){
                                        puedeConfirmar=false;
                                    }
                                }
                            }
                        }
                        if(puedeConfirmar==true){
                            JOptionPane.showMessageDialog(null, "Cambios guardados.");
                            jugadores[0]=new Jugadores("Equipo 1",jugador1,fichaDeEquipo1);
                            jugadores[1]=new Jugadores("Equipo 2",jugador2,fichaDeEquipo2);
                            jugadores[2]=new Jugadores("Equipo 3",jugador3,fichaDeEquipo3);
                            llamar2.guardarJugadores(jugadores, "datos.Jugadores");
                            cantidadCartas=6;
                            paraIndice=1;
                            configuracion=true;
                            confi=new GuradarConfiguracion(cantidadJugadores,cantidadCartas,paraIndice,configuracion,efectodeReyes,efectodeReinas);
                            llamar1.guardarConfiguracion(confi, "datos.Configuracion");
                            new Menu_Principal().setVisible(true);
                            this.setVisible(false);
                        }else{
                            JOptionPane.showMessageDialog(null, "Asegurese de no repetir los jugadores.");
                        }
                    }
                }
                break;
            case 4:
                if(jugador1.equals("")&&jugador2.equals("")&&jugador4.equals("")&&jugador5.equals("")){
                    JOptionPane.showMessageDialog(null, "Asegurese de escoger los jugadores.");
                    puedeConfirmar=false;
                }else{
                    if(fichaDeEquipo1.equals(fichaDeEquipo2)&&fichaDeEquipo2.equals(fichaDeEquipo1)){
                        JOptionPane.showMessageDialog(null, "Asegurese de escoger bien las fichas.");
                        puedeConfirmar=false;
                    }else{
                        for(int indice=0;indice<4;indice++){
                            for(int contar=0;contar<4;contar++){
                                if(indice!=contar){
                                    if(revisar[indice].equals(revisar[contar])){
                                        puedeConfirmar=false;
                                    }
                                }
                            }
                        }
                        if(puedeConfirmar==true){
                            JOptionPane.showMessageDialog(null, "Cambios guardados.");
                            jugadores[0]=new Jugadores("Equipo 1",jugador1,fichaDeEquipo1);
                            jugadores[1]=new Jugadores("Equipo 1",jugador4,fichaDeEquipo1);
                            jugadores[2]=new Jugadores("Equipo 2",jugador2,fichaDeEquipo2);
                            jugadores[3]=new Jugadores("Equipo 2",jugador5,fichaDeEquipo2);
                            llamar2.guardarJugadores(jugadores, "datos.Jugadores");
                            cantidadCartas=7;
                            paraIndice=1;
                            configuracion=true;
                            confi=new GuradarConfiguracion(cantidadJugadores,cantidadCartas,paraIndice,configuracion,efectodeReyes,efectodeReinas);
                            llamar1.guardarConfiguracion(confi, "datos.Configuracion");
                            new Menu_Principal().setVisible(true);
                            this.setVisible(false);
                        }else{
                            JOptionPane.showMessageDialog(null, "Asegurese de no repetir los jugadores.");
                        }
                    }
                }
                break;
            case 6:
                if(jugador1.equals("")&&jugador2.equals("")&&jugador3.equals("")&&jugador4.equals("")
                        &&jugador5.equals("")&&jugador6.equals("")){
                    JOptionPane.showMessageDialog(null, "Asegurese de escoger los jugadores.");
                    puedeConfirmar=false;
                }else{
                    if(fichaDeEquipo1.equals(fichaDeEquipo2)&&fichaDeEquipo1.equals(fichaDeEquipo3)
                            &&fichaDeEquipo2.equals(fichaDeEquipo1)&&fichaDeEquipo2.equals(fichaDeEquipo3)
                            &&fichaDeEquipo3.equals(fichaDeEquipo1)&&fichaDeEquipo3.equals(fichaDeEquipo2)){
                        JOptionPane.showMessageDialog(null, "Asegurese de escoger bien las fichas.");
                        puedeConfirmar=false;
                    }else{
                        for(int indice=0;indice<6;indice++){
                            for(int contar=0;contar<6;contar++){
                                if(indice!=contar){
                                    if(revisar[indice].equals(revisar[contar])){
                                        puedeConfirmar=false;
                                    }
                                }
                            }
                        }
                        if(puedeConfirmar==true){
                            JOptionPane.showMessageDialog(null, "Cambios guardados.");
                            jugadores[0]=new Jugadores("Equipo 1",jugador1,fichaDeEquipo1);
                            jugadores[1]=new Jugadores("Equipo 1",jugador4,fichaDeEquipo1);
                            jugadores[2]=new Jugadores("Equipo 2",jugador2,fichaDeEquipo2);
                            jugadores[3]=new Jugadores("Equipo 2",jugador5,fichaDeEquipo2);
                            jugadores[4]=new Jugadores("Equipo 3",jugador3,fichaDeEquipo3);
                            jugadores[5]=new Jugadores("Equipo 3",jugador6,fichaDeEquipo3);
                            llamar2.guardarJugadores(jugadores, "datos.Jugadores");
                            cantidadCartas=5;
                            paraIndice=3;
                            configuracion=true;
                            confi=new GuradarConfiguracion(cantidadJugadores,cantidadCartas,paraIndice,configuracion,efectodeReyes,efectodeReinas);
                            llamar1.guardarConfiguracion(confi, "datos.Configuracion");
                            new Menu_Principal().setVisible(true);
                            this.setVisible(false);
                        }else{
                            JOptionPane.showMessageDialog(null, "Asegurese de no repetir los jugadores.");
                        }
                    }
                }
                break;  
            case 8:
                if(jugador1.equals("")&&jugador2.equals("")&&jugador4.equals("")&&jugador5.equals("")
                        &&jugador7.equals("")&&jugador8.equals("")&&jugador9.equals("")&&jugador10.equals("")){
                    JOptionPane.showMessageDialog(null, "Asegurese de escoger los jugadores.");
                    puedeConfirmar=false;
                }else{
                    if(fichaDeEquipo1.equals(fichaDeEquipo2)&&fichaDeEquipo2.equals(fichaDeEquipo1)){
                        JOptionPane.showMessageDialog(null, "Asegurese de escoger bien las fichas.");
                        puedeConfirmar=false;
                    }else{
                        for(int indice=0;indice<8;indice++){
                            for(int contar=0;contar<8;contar++){
                                if(indice!=contar){
                                    if(revisar[indice].equals(revisar[contar])){
                                        puedeConfirmar=false;
                                    }
                                }
                            }
                        }
                        if(puedeConfirmar==true){
                            JOptionPane.showMessageDialog(null, "Cambios guardados.");
                            jugadores[0]=new Jugadores("Equipo 1",jugador1,fichaDeEquipo1);
                            jugadores[2]=new Jugadores("Equipo 1",jugador4,fichaDeEquipo3);
                            jugadores[4]=new Jugadores("Equipo 1",jugador7,fichaDeEquipo2);
                            jugadores[6]=new Jugadores("Equipo 1",jugador9,fichaDeEquipo2);
                            jugadores[1]=new Jugadores("Equipo 2",jugador2,fichaDeEquipo2);
                            jugadores[3]=new Jugadores("Equipo 2",jugador5,fichaDeEquipo1);
                            jugadores[5]=new Jugadores("Equipo 2",jugador8,fichaDeEquipo3);
                            jugadores[7]=new Jugadores("Equipo 2",jugador10,fichaDeEquipo3);
                            llamar2.guardarJugadores(jugadores, "datos.Jugadores");
                            cantidadCartas=4;
                            paraIndice=3;
                            configuracion=true;
                            confi=new GuradarConfiguracion(cantidadJugadores,cantidadCartas,paraIndice,configuracion,efectodeReyes,efectodeReinas);
                            llamar1.guardarConfiguracion(confi, "datos.Configuracion");
                            new Menu_Principal().setVisible(true);
                            this.setVisible(false);
                        }else{
                            JOptionPane.showMessageDialog(null, "Asegurese de no repetir los jugadores.");
                        }
                    }
                }
                break;    
        }
    }//GEN-LAST:event_confirmarActionPerformed

    private void equipoDeJugadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_equipoDeJugadorItemStateChanged
        // TODO add your handling code here:
        equipo=(String)equipoDeJugador.getSelectedItem();
        switch(equipo){
            case "Equipo 1":
                nombreJugador1.setText(usuarioLogin);
                nombreJugador1.setVisible(true);
                nombreJugador2.setVisible(false);
                nombreJugador3.setVisible(false);
                jComboBox1.setVisible(false);
                jComboBox2.setVisible(true);
                jComboBox3.setVisible(true);
                break;
            case "Equipo 2":
                nombreJugador2.setText(usuarioLogin);
                nombreJugador1.setVisible(false);
                nombreJugador2.setVisible(true);
                nombreJugador3.setVisible(false);
                jComboBox1.setVisible(true);
                jComboBox2.setVisible(false);
                jComboBox3.setVisible(true);
                break;
            case "Equipo 3":
                nombreJugador3.setText(usuarioLogin);
                nombreJugador1.setVisible(false);
                nombreJugador2.setVisible(false);
                nombreJugador3.setVisible(true);
                jComboBox1.setVisible(true);
                jComboBox2.setVisible(true);
                jComboBox3.setVisible(false);
                break;
        }
    }//GEN-LAST:event_equipoDeJugadorItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> CantidadJugadores;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel efectoDeReyes;
    private javax.swing.JLabel efectoDeReyes1;
    public static javax.swing.JComboBox<String> efectoReinas;
    public static javax.swing.JComboBox<String> efectoReyes;
    public static javax.swing.JComboBox<String> equipoDeJugador;
    public static javax.swing.JComboBox<String> fichasdequipo1;
    public static javax.swing.JComboBox<String> fichasdequipo2;
    public static javax.swing.JComboBox<String> fichasdequipo3;
    private javax.swing.JLabel fichasequipo1;
    private javax.swing.JLabel fichasequipo2;
    private javax.swing.JLabel fichasequipo3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jugadoresdeequipo1;
    private javax.swing.JLabel jugadoresdeequipo2;
    private javax.swing.JLabel jugadoresdeequipo3;
    private javax.swing.JLabel nombreJugador1;
    private javax.swing.JLabel nombreJugador2;
    private javax.swing.JLabel nombreJugador3;
    // End of variables declaration//GEN-END:variables
}
