/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Clases.Usuarios;
import static Clases.Funciones.guardarUsers;
import static Clases.Funciones.leerUsers;
import static Main.Inicio_de_Sesion.llamar;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author adalb
 */
public class Crear_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Crear_Usuario
     */
    public Crear_Usuario() {
        initComponents();
    }
    public static ArrayList<Usuarios> users=new ArrayList<>();
    public static ArrayList<Usuarios> usersGuardados=new ArrayList<>();
    static Date fechaCrear=new Date();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsuarioTextbox = new javax.swing.JTextField();
        NombreTextbox = new javax.swing.JTextField();
        PasswordTextbox = new javax.swing.JPasswordField();
        ConfirmPasswordTextbox = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        Crear_usuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(UsuarioTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 345, -1));
        getContentPane().add(NombreTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 345, -1));
        getContentPane().add(PasswordTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 345, -1));
        getContentPane().add(ConfirmPasswordTextbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 299, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesTablero/registra_usuarios.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 338));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 100, 30));

        Crear_usuario.setText("Crear Usuario");
        Crear_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Crear_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Crear_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Crear_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Crear_usuarioActionPerformed
        // TODO add your handling code here:
        usersGuardados=leerUsers("datos.bin");
        String usuarioCrear=UsuarioTextbox.getText();
        String nombreCrear=NombreTextbox.getText();
        String contraseñaCrear=PasswordTextbox.getText();
        String confirmarcontraseña=ConfirmPasswordTextbox.getText();
        if(usuarioCrear.isEmpty()||nombreCrear.isEmpty()||contraseñaCrear.isEmpty()||confirmarcontraseña.isEmpty()){
            JOptionPane.showMessageDialog(null, "Asegurese de llenar todos los campos.");
        }else{
            if(contraseñaCrear.equals(confirmarcontraseña)){
                if(usersGuardados!=null){
                    if(llamar.siExiste(usuarioCrear)){
                        JOptionPane.showMessageDialog(null, "Usuario ya existe.");
                    }else{
                        users=leerUsers("datos.bin");
                        ArrayList<String> historial=new ArrayList<>();
                        users.add(new Usuarios(usuarioCrear,nombreCrear,contraseñaCrear,fechaCrear,0,historial));
                        guardarUsers(users, "datos.bin");
                        JOptionPane.showMessageDialog(null, "Creo su usuario exitosamente.");
                        new Inicio_de_Sesion().setVisible(true);
                        this.setVisible(false);
                    }
                }else{
                    ArrayList<String> historial=new ArrayList<>();
                    users.add(new Usuarios(usuarioCrear,nombreCrear,contraseñaCrear,fechaCrear,0,historial));
                    guardarUsers(users, "datos.bin");
                    JOptionPane.showMessageDialog(null, "Creo su usuario exitosamente.");
                    new Inicio_de_Sesion().setVisible(true);
                    this.setVisible(false);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Asegurese de confirmar su contraseña correctamente.");
            }
        }
        
    }//GEN-LAST:event_Crear_usuarioActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        new Inicio_de_Sesion().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crear_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crear_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crear_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crear_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crear_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPasswordTextbox;
    private javax.swing.JButton Crear_usuario;
    private javax.swing.JTextField NombreTextbox;
    private javax.swing.JPasswordField PasswordTextbox;
    private javax.swing.JTextField UsuarioTextbox;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
